authors:
  jmeng:
    name: Jakob Meng
    description: https://github.com/jm1
    avatar: https://www.okd.io/img/okd-panda-flat_rocketeer_with_number.svg
  dmueller:
    name: Diane Mueller
    description: https://github.com/dmueller2001
    avatar: https://www.okd.io/img/okd-panda-flat_rocketeer_with_number.svg